In [1]:
import statsmodels.api as sm

In [2]:
# Fetch the dataset from R's core datasets repository
mtcars = sm.datasets.get_rdataset("mtcars", "datasets").data

print(mtcars.head())

                    mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
rownames
Mazda RX4          21.0    6  160.0  110  3.90  2.620  16.46   0   1     4
Mazda RX4 Wag      21.0    6  160.0  110  3.90  2.875  17.02   0   1     4
Datsun 710         22.8    4  108.0   93  3.85  2.320  18.61   1   1     4
Hornet 4 Drive     21.4    6  258.0  110  3.08  3.215  19.44   1   0     3
Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3

                   carb
rownames
Mazda RX4             4
Mazda RX4 Wag         4
Datsun 710            1
Hornet 4 Drive        1
Hornet Sportabout     2

In [5]:
import numpy as np

In [4]:
import pandas as pd

In [6]:
df_subset = mtcars[['hp', 'mpg']]

In [7]:
df_subset.head()

                    hp   mpg
rownames
Mazda RX4          110  21.0
Mazda RX4 Wag      110  21.0
Datsun 710          93  22.8
Hornet 4 Drive     110  21.4
Hornet Sportabout  175  18.7

In [8]:
df_final = df_subset.reset_index(drop=True)
df_final.head()

    hp   mpg
0  110  21.0
1  110  21.0
2   93  22.8
3  110  21.4
4  175  18.7

In [9]:
y = df_final['mpg'].to_numpy()
X_raw = df_final['hp'].to_numpy()

In [10]:
X = np.vander(X_raw, 2) # creates a column of 1's in X_raw

In [11]:
beta = np.linalg.inv(X.T @ X) @ X.T @ y

In [12]:
slope = beta[0]
intercept = beta[1]

print(f"Intercept: {intercept:.4f}")
print(f"Slope (hp): {slope:.4f}")
print(f"\nPrediction Equation: mpg = {intercept:.4f} + ({slope:.4f} * hp)")

Intercept: 30.0989
Slope (hp): -0.0682

Prediction Equation: mpg = 30.0989 + (-0.0682 * hp)

In [13]:
# 1. Prepare your data
X = df_final['hp']
y = df_final['mpg']

# 2. Statsmodels requires explicitly adding a constant (intercept) column
X = sm.add_constant(X)
# 3. Fit the OLS model
model = sm.OLS(y, X).fit()

# 4. Print the full regression analysis report
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.602
Model:                            OLS   Adj. R-squared:                  0.589
Method:                 Least Squares   F-statistic:                     45.46
Date:                Thu, 01 Oct 2026   Prob (F-statistic):           1.79e-07
Time:                        06:54:09   Log-Likelihood:                -87.619
No. Observations:                  32   AIC:                             179.2
Df Residuals:                      30   BIC:                             182.2
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         30.0989      1.634     18.421      0.000      26.762      33.436
hp            -0.0682      0.010     -6.742      0.000      -0.089      -0.048
==============================================================================
Omnibus:                        3.692   Durbin-Watson:                   1.134
Prob(Omnibus):                  0.158   Jarque-Bera (JB):                2.984
Skew:                           0.747   Prob(JB):                        0.225
Kurtosis:                       2.935   Cond. No.                         386.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.